// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsfbythbnhnypqqjetdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZmJ5dGhibmhueXBxcWpldGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTgxODMsImV4cCI6MjA1OTc3NDE4M30.YQatQBxy3SHhVNRDVXHqsvtbxiia-9EQlcEWT0lBbu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);